export interface CalculationUC {
  acceptanceLimitMin: string;
  acceptanceLimitMax: string;
  id: number;
  label: string;
  selectedStandardPreparationLabel: string | null;
  selectedSamplePreparationLabel: string | null;
  areaOfStandard: string | null;
  areaOfSample1: string | null;
  areaOfSample2: string | null;
  areaOfSample3: string | null;
  areaOfSample4: string | null;
  areaOfSample5: string | null;
  areaOfSample6: string | null;
  areaOfSample7: string | null;
  areaOfSample8: string | null;
  areaOfSample9: string | null;
  areaOfSample10: string | null;
  purity: string;
  mWBase: string | null;
  mWSalt: string | null;
  calculationResultUnit: string | null;
  calculationResultTablet1: string | null;
  calculationResultTablet2: string | null;
  calculationResultTablet3: string | null;
  calculationResultTablet4: string | null;
  calculationResultTablet5: string | null;
  calculationResultTablet6: string | null;
  calculationResultTablet7: string | null;
  calculationResultTablet8: string | null;
  calculationResultTablet9: string | null;
  calculationResultTablet10: string | null;
  sw1: string | null;
  claim: string | null;
  v1: string | null;
  v2: string | null;
  v3: string | null;
  v4: string | null;
  v5: string | null;
  v6: string | null;
  v7: string | null;
  v8: string | null;
  v9: string | null;
  v10: string | null;
  v11: string | null;
  v12: string | null;
  v13: string | null;
  v14: string | null;
  mgPerTabletResultTablet1: string | null;
  mgPerTabletResultTablet2: string | null;
  mgPerTabletResultTablet3: string | null;
  mgPerTabletResultTablet4: string | null;
  mgPerTabletResultTablet5: string | null;
  mgPerTabletResultTablet6: string | null;
  mgPerTabletResultTablet7: string | null;
  mgPerTabletResultTablet8: string | null;
  mgPerTabletResultTablet9: string | null;
  mgPerTabletResultTablet10: string | null;
  mgPerTabletResultUnit: string | null;
}